
const NOMBRES_OBJETOS = {
    cama_king: "Cama King",
    cama_super_king: "Cama Super King",
    cama_1_5: "Cama de 1.5",
    cama_2: "Cama de 2 plazas",
    refrigerador_pequeno: "Refrigerador",
    refrigerador_grande: "Refrigerador de dos puertas verticales",
    lavadora: "Lavadora",
    lavadora_secadora: "Lavadora Secadora",
    sofa_pequeno: "Sofá Pequeño",
    sofa_grande: "Sofá Grande",
    tv_grande: "Televisor Grande",
    tv_pequeno: "Televisor Pequeño",
    escritorio_pequeno: "Escritorio Pequeño",
    escritorio_grande: "Escritorio Grande",
    silla_comedor: "Silla de Comedor",
    mesa_8: "Mesa de Comedor (8 personas)",
    mesa_6: "Mesa de Comedor (6 personas)",
    mesa_4: "Mesa de Comedor (4 personas)",
    rack_tv_pequeno: "Rack de TV Pequeño",
    rack_tv_grande: "Rack de TV Grande",
    comoda_grande: "Cómoda Grande",
    comoda_pequena: "Cómoda Pequeña",
    veladores: "Veladores",
    maletas: "Maletas",
    bolsas: "Bolsas",
    cajas: "Cajas",
    respaldo_cama: "Respaldo de Cama",
    poltrona: "Poltrona",
    banqueta: "Banqueta",
    mesa_entrada: "Mesa de Entrada",
    mesa_centro: "Mesa de Centro",
    silla_escritorio: "Silla de Escritorio",
    terraza_grande: "Juego Terraza Grande",
    terraza_pequena: "Juego Terraza Pequeño",
    parrillera_grande: "Parrillera Grande",
    parrillera_pequena: "Parrillera Pequeña"
};

export default NOMBRES_OBJETOS